# Changes here will be overwritten by Copier
_commit: 0.14.2
_src_path: gh:bhklab/bhklab-project-template
additional_authors_raw: James Bannon
author_email: bhklab.michaeltran@gmail.com
author_full_name: Michael Tran
github_username: mtran-code
has_additional_authors: true
project_description: Modern Python implementation of SNF package
project_name: SNF2
project_slug: snf2
publish_to_github: true
python_version: '3.13'
repo_location: bhklab
