name: Check

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.10.1
        with:
          pixi-version: v0.77.0
          environments: dev
          cache: true

      - name: Run checks
        run: pixi run --locked -e dev check
